#ifndef __MSG_ID_DEFINE_H
#define __MSG_ID_DEFINE_H



//全局的消息号范围约定：
#define    NONE_MODULE_MSGID_BASE               0              //无方向性的信令交互   0~499
#define    PROPOSER_ACCEPTOR_MSGID_BASE         500            //   500~999


enum MessageType
{
	//COMMON
	PRO_SYS_HEART_REQ = NONE_MODULE_MSGID_BASE,        //消息体为空
	PRO_SYS_HEART_ACK = NONE_MODULE_MSGID_BASE + 1,    //消息体为空
	START_CONNECT_REQ = NONE_MODULE_MSGID_BASE + 2,    //(SERVTYPE int, SERVPORT int, APPID int, SETID int,SERIAL_NO int)
	START_CONNECT_ACK = NONE_MODULE_MSGID_BASE + 3,    //(SERVTYPE int, APPID int, SETID int, SERIAL_NO int)

	//proposer 与 acceptor的交互////////////////////////////////
	PROPOSER_ACCEPTOR_PREPARE_REQ = PROPOSER_ACCEPTOR_MSGID_BASE,
	ACCEPTOR_PROPOSER_PREPARE_ACK = PROPOSER_ACCEPTOR_MSGID_BASE + 1,

	PROPOSER_ACCEPTOR_ACCEPT_REQ = PROPOSER_ACCEPTOR_MSGID_BASE + 2,
	ACCEPTOR_PROPOSER_ACCEPT_ACK = PROPOSER_ACCEPTOR_MSGID_BASE + 3,
	ACCEPTOR_PROPOSER_ACCEPT_NACK = PROPOSER_ACCEPTOR_MSGID_BASE + 4,

	//BOARDCAST_MASTER_INFO_NTY = PROPOSER_ACCEPTOR_MSGID_BASE + 4,
};

#endif
